### ISSUE TITLE
Plugin causing errors in with Joomla Menus

### ISSUE THREAD

**Issue by idlwebinc** [nekto-kotik/sqlantern-cms-modules#1]
Issue appeared while trying a Save menu/action in Joomla 4.4 admin.

Please see screenshot: https://app.screencast.com/T2Yeih1uVYEUQ

**Comment by nekto-kotik** [comment]
Thank you for submitting such a critical bug!
Coincidentally, a new version will be published later today, and the fix will be included (shamefully, it's a dev-only unused code).
Feel free to disable the plugin until then.

**Comment by nekto-kotik** [comment]
The new version has just been published, and it takes care of this bug (v1.9.6).
I tested it in Joomla 4, and the error is now gone (Joomla 3 wasn't affected, surprisingly).

You'll need to _uninstall_ current version first, and then install the new version. Upgrade doesn't fully work for some reason (it _partially_ works, I'll look into it next).

Please, let me know if the error is still there for you with the latest version and thanks again!
